### ISSUE TITLE
[Feature]: Better search idea

### ISSUE THREAD

**Issue by TariqJandaly** [react-icons/react-icons#796] opened 2023-08-12 18:31 UTC
### Describe

When you search for a new icon if you add any spaces it will not work because no icons have a space in its name, like when you want to search for a clip board icon you will need to type 'clipboard' and if you type 'clip board' you will get 'no icons found'

### Solution

You could get the new search input idea from using this code below:

```ts
// Getting the search input
let search = 'clip board'

// Splitting the search input
search = search.split(" ") // You will get an output of an array with the value of ["clip", "board"]

// Finally you could join them to get the correct search input
search = search.join("") // You will get an output of a string with the value of "clipboard"

// Use the search in your input as you want

// -------------------------
// To use it with useState

const [search, setSearch] = useState<string>("clip board")

// Splitting the search input
setSearch((s) => s.split(" ")) // You will get an output of an array with the value of ["clip", "board"]

// Finally you could join them to get the correct search input
setSearch((s) => s.join("")) // You will get an output of a string with the value of "clipboard"

```

### Additional context

And I want to thank you all for your work to bring this amazing project for us <3

**Comment by Bismay5467** [comment] 2023-09-11 18:50
@kamijin-fanta @TariqJandaly could you please assign this issue to me? I would love to resolve it.

**Comment by kimtaejin3** [comment] 2023-09-17 11:23
@Bismay5467 I wanna implement this feature too! Are you implementing it now? if you are ok, I wan to resolve it

**Comment by Bismay5467** [comment] 2023-09-17 16:35
@kimtaejin3 I'd been travelling for a few days. I'll start working on this issue tomorrow.

**Comment by Bismay5467** [comment] 2023-09-18 20:51
@kimtaejin3, if you're up for it, you can go ahead and start working on this issue. I've been tied up with some other tasks recently. Once that's done, I might pick up another issue. If you require any assistance in the meantime, please don't hesitate to reach out – I'd be happy to assist.

**Comment by kimtaejin3** [comment] 2023-09-18 23:49
@Bismay5467 Thank you :)

**Comment by Hamjaster** [comment] 2023-09-22 20:24
Is this issue still open, I'd like to work on it :)

**Comment by kimtaejin3** [comment] 2023-09-23 02:57
@Hamjaster one of my coworkers already implemented this feature and he is gonna send a pull request soon.

**Comment by Hamjaster** [comment] 2023-09-23 03:20
Ok, I wanna contribute to other issues the BUT confirm that Is the maintainer still merging pull requests??

**Comment by bombillazo** [comment] 2023-09-24 01:21
I'd also love this feature!

@kamijin-fanta, any plan to add other trusted maintainers to the library? I think that will alleviate the workload of reviewing PRs, managing all the issues, and avoid the library getting stale/stagnant due to a key-man bottleneck.

**Comment by kamijin-fanta** [comment] 2023-09-26 07:26
Thanks.

I have not been able to make the PreviewSite modifications due to the high priority of internal fixes at the moment. Perhaps this Issue is a duplicate of #620 and the Pull Request was submitted at #621. Once the conflicts are resolved, they can be merged.

Close this Issue because it is a duplicate.

**Closed by kamijin-fanta** 2023-09-26 07:26 UTC
Labels: preview-site
