### ISSUE TITLE
Warning during development

### ISSUE THREAD

**Issue by Eyob94** [react-icons/react-icons#650] opened 2022-11-23 08:49 UTC
**Describe the bug**
The warning was raised about the "main" field in the package.json file

**Expected behavior**
There shouldn't have been any warning

**Screenshots**
![image](https://user-images.githubusercontent.com/103565328/203504174-84bbea21-deee-4d04-9fa5-c61e07934bcf.png)

**Desktop (please complete the following information):**

- Device: PC
- OS: Windows 10
- Version 4.6.0

**Comment by daveidivide** [comment] 2022-12-02 09:04
Same thing happening here.

On a Mac in a NextJS project.

Very strange.

**Comment by samuelko123** [comment] 2022-12-03 04:18
Same here.
Windows 10.
Version 4.7.1.

**Comment by wweaver** [comment] 2022-12-15 18:39
Duplicate of #509

**Comment by kamijin-fanta** [comment] 2023-03-08 05:57
Discussed in #509

**Closed by kamijin-fanta** 2023-03-08 05:57 UTC
Labels: Bug
