### ISSUE TITLE
[Feature]: Support Native ESM

### ISSUE THREAD

**Issue by shun-shobon** [react-icons/react-icons#717] opened 2023-04-19 02:10 UTC
### Describe

Hello. Thank you for developing this wonderful library.

Currently, this library provides both CommonJS format files and ES Module format files. However, the ESM files are only specified as `"module"` in package.json. [`"module"` is not supported by Node.js](https://nodejs.org/api/packages.html#dual-commonjses-module-packages), and Node.js running as ESM cannot import ESM files from this library.

To enable Node.js to import ESM files, you should add `"type": "module"` to package.json and provide CommonJS format files as `.cjs`.

### Solution

First, add `"type": "module"` to `package.json` to indicate that the library is provided by ESM. Next, rewrite the file extensions provided by CommonJS from `.js` to `.cjs` and the file extensions provided by ESM from `.esm.js` to `.js`. This will work in CommonJS by auto-completion of `main` and extensions, and in ESM by directly specifying `index.js`. This should also work well in TypeScript with `"moduleResolution": "node16"` set.
[Conditional exports](https://nodejs.org/api/packages.html#conditional-exports) would also be better supported, but since there are so many subdirectories in this library, I think it may not be necessary to do this at first.

### Additional context

I would like to be able to import ESM and CommonJS files in the standard Node.js functionality. I would love to work on this issue and would love to send you a PR!

**Comment by Lord-Valen** [comment] 2023-04-27 04:37
I suspect that this is the cause of TS2307 when using node16 module resolution.

**Comment by user1m** [comment] 2023-07-07 23:03
any progress on this? would be happy to support as well. running into issues using this lib in ESM SSR project

**Comment by LorenzoBloedow** [comment] 2023-07-23 21:12
Having this problem with the Vercel integration of Astro.js, during SSR.

Happy to help as well!

**Comment by LorenzoBloedow** [comment] 2023-07-24 16:56
I made a PR to fix this, if anyone is reading this and needs a solution right now, just install my fork under the react-icons alias: `npm i react-icons@npm:@lorenzobloedow/react-icons`

**Comment by stivncastillo** [comment] 2023-08-09 21:09
> I made a PR to fix this, if anyone is reading this and needs a solution right now, just install my fork under the react-icons alias: `npm i react-icons@npm:@lorenzobloedow/react-icons`

@LorenzoBloedow 

I'm having this error with your fork: [mypath]/node_modules/react-icons/lib' is not supported resolving ES modules imported from [mypath]/node_modules/react-icons/io/index.mjs

**Comment by LorenzoBloedow** [comment] 2023-08-10 13:32
> > I made a PR to fix this, if anyone is reading this and needs a solution right now, just install my fork under the react-icons alias: `npm i react-icons@npm:@lorenzobloedow/react-icons`
> 
> @LorenzoBloedow
> 
> I'm having this error with your fork: [mypath]/node_modules/react-icons/lib' is not supported resolving ES modules imported from [mypath]/node_modules/react-icons/io/index.mjs

Can you send me your `tsconfig.json` and node version?

**Comment by stivncastillo** [comment] 2023-08-10 14:02
@LorenzoBloedow 

tsconfig.json:
```
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react",
    "baseUrl": ".",
    "paths": {
      "@components/*": ["src/components/*"],
      "@layouts/*": ["src/layouts/*"]
    }
  },
  "exclude": ["node_modules", "src/**/*.mdx"]
}
```

Node v16.16.0

**Comment by dvnrsn** [comment] 2023-11-14 00:01
For me it works as long as I append "index.js" to all of my imports which is annoying but workable 🤔 

```ts
import { AiOutlineMenu } from "react-icons/ai/index.js";

**Closed** 2024-01-10 05:58 UTC
