### ISSUE TITLE
Missing RiOrganizationChart Icon

### ISSUE THREAD

**Issue by brunoandradebr** [react-icons/react-icons#438] opened 2021-05-08 17:03 UTC
Trying to import RiOrganizationChart but get : 

Attempted import error: 'RiOrganizationChart' is not exported from 'react-icons/ri'

=/

**Comment by hacknug** [comment] 2021-06-22 09:39
I know your issue is older but I'd call this a duplicate of #446 and followup there.

**Comment by hacknug** [comment] 2021-06-22 12:07
I've published a fork of this package with all of the missing Remix icons. Details on https://github.com/react-icons/react-icons/issues/446#issuecomment-865823421

**Closed** 2023-10-16 21:18 UTC
