### ISSUE TITLE
'react-icons' module not found on server-side

### ISSUE THREAD

**Issue by neomusic** [react-icons/react-icons#235] opened 2019-05-15 08:43 UTC
I tried to implements this package on my NextJs project, but with latest version of react-icons the package is not found on server-side.
With 3.2.2 version it works.
I noticed a little difference between 3.2.2 and 3.7.0. The index.mjs is missing. Is related?

NextJs: 7.0.2
React: 16.4.2
Node: 10.14

**Comment by Delkathes** [comment] 2019-05-18 09:14
How weird. My Next app was running on dev script. I installed 'react-icons' package. Hot reload implemented it. I got my icons displayed while I was working. But suddenly, after a page refresh or a npm run script refresh, I lost them and the app just couldn't find 'react-icons'

**Comment by 0str1ch** [comment] 2019-05-20 17:45
I can confirm this behavior, as well. I believe it has something to do with IconContext.Provider.

**Comment by exogen** [comment] 2019-05-30 06:41
See comments here: https://github.com/react-icons/react-icons/issues/230#issuecomment-490236294

It's because of the double-`package.json` approach that react-icons uses, which is supported by webpack but not Node.

**Comment by hwangar** [comment] 2019-06-14 17:30
Same here... if it helps last version usable is 3.6.0: 3.6.1 crashes and I confirm too it's sth with IconContext.Provider

**Comment by AslamPangestu** [comment] 2019-07-19 04:16
I have the same issue to. But, first i have trouble with styled-component when first render is not applied. when i use this tutorial, it's work
https://dev.to/aprietof/nextjs--styled-components-the-really-simple-guide----101c

**Comment by shatodj** [comment] 2019-08-23 15:43
The same here trying to work with Parcel bundler compiling my server.ts :(

**Comment by olaj** [comment] 2019-11-27 09:23
Same here. Is there any workaround for this? Guess i will survive without this feature though.

**Comment by schnerd** [comment] 2019-12-07 22:38
Minimal reproduction:
https://github.com/schnerd/react-icons-issue

Running `require('react-icons');` in node.js throws a fatal error. Requiring individual icons works fine, so it seems like this only affects developers who need to import top-level things like IconContext or Typescript types during server-side rendering.

@exogen's hypothesis in https://github.com/react-icons/react-icons/issues/230#issuecomment-490236294 seems accurate. I attempted consolidating the two package.json files and it seemed to resolve the issue in my project, although maybe it has unintended side effects: https://github.com/schnerd/react-icons/commit/df4e9f2a83368d77f436db1b4e80ee6995c58e7c

@kamijin-fanta thoughts about this approach? should I open a PR?

**Comment by neomusic** [comment] 2019-12-08 15:20
I created a pull-request to solve this issue. I hope it is accepted

Check out my [PR](https://github.com/react-icons/react-icons/pull/273)

**Comment by aepyornis** [comment] 2019-12-09 17:41
I was able to fix the issue importing `IconcContext.Provider` by simply adding **/lib** to the import statement.

` import { IconContext } from "react-icons" ` fails with the error _Cannot find module 'node_modules/react-icons/lib'. Please verify that the package.json has a valid "main" entry_ 

Importing IconContext from react-icons/lib worked for me:

``` js 
import { IconContext } from "react-icons/lib" 
```

**Comment by jacobhixon47** [comment] 2020-01-09 17:00
Can confirm this issue is still happening, and that the above solution of appending `/lib` to the react-icons import works for me as well. 

A little worried that when a fix gets merged, it'll break the `/lib` workaround, but I'll cross that bridge when I get there I suppose.

**Comment by kinavi** [comment] 2020-03-11 08:59
I was helped by updating react-icons from 3.8 to 3.9

**Comment by kamijin-fanta** [comment] 2023-03-08 05:56
resolved in #273

**Closed by kamijin-fanta** 2023-03-08 05:56 UTC
