### ISSUE TITLE
[Bug]: Cannot find module: 'react-icons/all'.

### ISSUE THREAD

**Issue by moda20** [react-icons/react-icons#740] opened 2023-05-29 16:57 UTC
### Describe the bug

I am trying to build a project with react-icons where i import an icon from `/all` like this : 
```
import {HiOutlineDocumentText} from "react-icons/all";
```
the build using react-scripts will error out with the message  `Cannot find module: 'react-icons/all'. Make sure this package is installed.`. this  didn't happen before though. 
I am still using node 14 as usual 

### Expected behavior

build correctly and import the icons.

### Minimal sample repository URL

http://

### Steps To Reproduce

- install react-icons 4.4 
- import `import {HiOutlineDocumentText} from "react-icons/all";`
- run `react-scripts build`

### Package version

4.4

**Comment by shifenhutu** [comment] 2023-05-30 16:32
same here   

on  ` "react-icons": "^4.9.0",`

**Comment by JoelNichols** [comment] 2023-05-30 19:46
This absolutely needs to be considered as a bug, and the previous fix shouldn't be regarded as a suitable solution.

Regardless of your views of whether or not the "all" import is acceptable, the simple fact is that many apps will have been developed making use of this.

**Comment by bastiengrignon** [comment] 2023-05-31 14:33
I have the same issue ! This should at leat be present in a release note (I always check release not not before upgrading to new version). But this is a breaking change so this should not have been present in a minor update...

**Comment by Viktoriya-D** [comment] 2023-06-01 15:45
So the issue is as follows, if you have this in package.json:
 "react-icons": "^4.8.0",
This will pull in the latest react-icons package which as of 4 days ago is 4.9.0.

If you look inside the new package, all.js file which imported all icons is missing.  As a result, everyone is getting an error that it cannot be found.  

From the stand-point of backwards compatibility this is broken b/c it would cause everyone using react-icons/all package reference to update their reference to get around this error.  

As a result it's a bug that should be fixed as soon as possible to avoid backwards compatibility issues.

**Comment by Viktoriya-D** [comment] 2023-06-01 15:49
To temporarily fix this problem update your package.json to say:
"react-icons" : "4.8.0"
and rerun npm i to pull in a version before 4.9.0. 
This should fix the issue for the time being until this bug is fixed.  Don't forget to add "^" back once it's fixed to ensure your package stays up to date.

**Comment by kamijin-fanta** [comment] 2023-06-02 01:28
very sorry. A maintainer who doesn't usually do releases publishes a package. This was to be released in 5.0.0.

**Closed** 2023-09-06 23:54 UTC
Labels: Bug

**Comment by kalwhyte** [comment] 2024-04-25 17:29
import { addToCart } from "../actions/cartActions";
import { RiArrowRightSLine, TiArrowRight, BsArrowBarRight} from "react-icons/all";
import {RiShoppingCart2Line} from "react-icons/all"
import { Checkbox } from '@chakra-ui/checkbox'
import {IoLogoFacebook,AiFillTwitterCircle,AiFillInstagram,AiFillShop,MdDoNotDisturb}  from "react-icons/all"
import { IoMdDoneAll } from 'react-icons/all';
import {BsArrowRight} from "react-icons/all"
import {FiFacebook, AiOutlineHeart, AiOutlineInstagram, IoLogoYoutube} from 'react-icons/all';
import {BsEnvelope, GiPositionMarker, HiOutlinePhone} from 'react-icons/all'
import {IoIosArrowForward,IoIosArrowBack} from 'react-icons/all'
import {AiFillStar,BsStarHalf,BsStar}  from "react-icons/all"
import { IoIosArrowDown } from 'react-icons/all';
import {BsFilter,AiOutlineSearch,IoMdClose} from 'react-icons/all'
import { VscChromeClose } from "react-icons/all";
import {RiShoppingCart2Line, IoCloseOutline, MdSearch, BsArrowRightShort, MdKeyboardArrowRight,IoLogOutOutline, CgProfile, IoChevronDownCircleOutline, IoMdArrowDropdown} from "react-icons/all"


**The fix**
import { addToCart } from "../actions/cartActions";
import { RiArrowRightSLine } from "react-icons/ri";
import { TiArrowRight } from "react-icons/ti";
import { BsArrowBarRight, BsArrowRight } from "react-icons/bs";
import { RiShoppingCart2Line } from "react-icons/ri";
import { Checkbox } from '@chakra-ui/checkbox';
import { IoLogoFacebook, AiFillTwitterCircle, AiFillInstagram, AiFillShop, MdDoNotDisturb } from "react-icons/io";
import { IoMdDoneAll, IoIosArrowForward, IoIosArrowBack, IoIosArrowDown, IoMdClose, IoLogOutOutline, CgProfile, IoChevronDownCircleOutline, IoMdArrowDropdown } from 'react-icons/io';
import { FiFacebook } from 'react-icons/fi';
import { AiOutlineHeart, AiOutlineInstagram, IoLogoYoutube } from 'react-icons/ai';
import { BsEnvelope, GiPositionMarker, HiOutlinePhone, BsFilter, AiOutlineSearch } from 'react-icons/bs';
import { VscChromeClose } from "react-icons/vsc";
import { AiFillStar, BsStarHalf, BsStar } from "react-icons/ai";
import { MdSearch, BsArrowRightShort, MdKeyboardArrowRight } from "react-icons/md";
